=== Mause/duckdb-web/_data/extension.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "aliases": {
            "type": "array",
            "items": {
                "type":"string"
            }
        },
        "extension_repository": {
            "type": "string"
        },
        "git_repository": {
            "type": "string"
        }
    },
    "required": ["name"]
}

=== Mause/duckdb-web/_data/extensions/fasql.json
{
    "$schema": "https://raw.githubusercontent.com/Mause/duckdb-web/third-party-extensions/_data/extension.schema.json",
    "name": "fasql",
    "git_repository": "https://github.com/wheretrue/fasql",
    "description": "DuckDB Extension for reading and writing FASTA and FASTQ Files",
    "extension_repository": "dbe.wheretrue.com/fasql/latest"
}
